apiVersion: v1
kind: Service
metadata:
  name: my-mealie-service
spec:
  type: NodePort
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30080 # You can specify a desired nodePort or let Kubernetes assign one
