apiVersion: v1
kind: Service
metadata:
  name: my-mealie-service
  namespace: mealie
spec:
  type: ClusterIP
  selector:
    app: mealie
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
       # You can specify a desired nodePort or let Kubernetes assign one
