apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Requests 500Mi of storage
  storageClassName:  local-path  # Can be used to specify a particular StorageClass, or left empty for default binding
